### ISSUE TITLE
Verify Spanish Translations

### ISSUE THREAD

**Issue by danielzeljko** [LangCorrect/server#129]
### Description:
The translations for this locale need to be verified for accuracy and context suitability.

### Tasks:
- [ ] Review all strings for grammatical errors
- [ ] Ensure that translations fit the context where they are used
- [ ] Correct any ambiguous phrases

**Comment by kayomi-codes** [comment]
In server/locale/es/LC_MESSAGES/django.po:
- **Line 110:** I believe this is meant to say "corrigió" instead of "Corregido". "Corregido" is the adjective "corrected", not the verb "correct" in past tense.
- **Line 144:** I would swap "Elemental" with "Básico", in Castillian Spanish people barely use "elemental". Although I'm not sure if this applies to other dialects, I do know that "básico" is a common word in all Spanish dialects.
- **Line 152:** Instead of "Intermedio-avanzado", you can just say "Intermedio alto". But this is just a suggestion, it isn't incorrect the way it is right now. Both are okay!
- **Line 168:** Again, I'm not very sure if this is a thing in other dialects but I have never heard of "membresías". I think "socios" is better known in all dialects in general.
- **Line 217:** I would change "Publicación añadida con éxito" with "Publicación subida con éxito". I believe both are fine but the first one bugged me a little.
- **Line *277:* "Están asociadas con" sounds a bit off, it is more common to use the preposition "a" ("están asociadas a").
- **Line 577~579:** I'd change the paragraph with "Establecer el género del narrador ayudará a los hablantes nativos a corregir cualquier error de género gramatical. Ten en cuenta que esto se refiere al narrador de un texto determinado, no necesariamente a ti."
- **Line 622:** Instead of "sitio", I would use "página" because "sitio" itself means "place" but "página" is understood from context that it refers to the website. It is more frequently used on the web.

So far I have read up to line 643, I will try to correct more things later if I'm free.

**Comment by danielzeljko** [comment]
Hi, @kayomi-codes

Thank you for taking the time to verify the translations! I'm pretty sure I updated the relevant string correctly. If it's not too much trouble, can you double check? (https://github.com/LangCorrect/server/commit/bbf2a30a34400cbb1f89cfe56ad470c3fd4173d5)

We actually have a GUI where you can update the strings directly through the platform. If this is something that you would be interested in, I would be more than happy to grant you the translator role!

**Comment by kayomi-codes** [comment]
Hello @danielzeljko!

I can absolutely double-check, I will review the strings as soon as possible and also try to verify the rest of lines I haven't been able to read.

Regarding the GUI, I'd be glad to help with Spanish translations! Feel free to assign me the translator role anytime.

**Comment by danielzeljko** [comment]
I appreciate that! What's your username on the platform?

**Comment by kayomi-codes** [comment]
No problem at all! My username is currently kintsugi_11.

**Comment by danielzeljko** [comment]
Are you able to access https://langcorrect.com/rosetta/files/project/?

**Comment by kayomi-codes** [comment]
It seems so! I haven't used this GUI before, but I can access the Spanish section so it should be working correctly.

**Comment by kayomi-codes** [comment]
I have just reviewed the commit and found a few grammatical incongruences, among them line 614. I will edit them through the GUI when I'm free.

**Comment by kayomi-codes** [comment]
I have reviewed all strings in the GUI and updated obsolete translations @danielzeljko

**Comment by danielzeljko** [comment]
That was quick! Thank you so much! 🙌

I edited the Last-Translator so your account email did not show. If you would like me to change it back, let me know! 

![image](https://github.com/LangCorrect/server/assets/115326106/6c533d5c-8171-48f4-af48-cebfe06ba9fd)

**Comment by kayomi-codes** [comment]
No problem! Glad to collaborate on the platform.

Note: I noticed the email change, it ends with @ langcorect.com, is it missing an R on purpose? Thank you for not showing my real email by the way! I prefer it that way.

**Comment by kayomi-codes** [comment]
After changing LangCorrect's interface to Spanish I saw an extra letter in a string that I didn't notice before. I updated the translation through the GUI once again so it can be committed, I apologize for the mistake @danielzeljko.

However, I also found out that there are a few parts of the website that don't translate into Spanish, especially buttons such as "Write" from the navigation bar and one or two drop-down menus like the one that appears below the "Teach, Learn, Following" section. Should this be included in a new issue?

**Comment by danielzeljko** [comment]
> I noticed the email change, it ends with @ langcorect.com, is it missing an R on purpose? 

No -- it was just a typo on my end!

> However, I also found out that there are a few parts of the website that don't translate into Spanish, especially buttons such as "Write" from the navigation bar and one or two drop-down menus like the one that appears below the "Teach, Learn, Following" section. Should this be included in a new issue?

![image](https://github.com/LangCorrect/server/assets/115326106/f2029f12-ff69-4b3f-8ba8-1d3073aa965a)

Seems like the issue is resolved. What most likely happened was me forgetting to recompile (refresh) the `.po` files. In any case, could you please check to see if they show up translated on your end now? Hopefully there is not underlying issue somewhere.

**Comment by kayomi-codes** [comment]
Unfortunately it still shows untranslated, how strange
![Screenshot_2023-12-29-12-41-28-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/LangCorrect/server/assets/132253104/5eff7073-2c0c-482e-bfbf-8502b026d456)

**Comment by danielzeljko** [comment]
I just replicated it on my phone. The drop-down items are translated. That button is an entirely different button than the one shown in desktop mode. I'll create an issue for this and get it fixed soon. Thanks for bringing it to my attention!

**Comment by kayomi-codes** [comment]
Oh I see! I hope it has an easy fix. I'd like to help with Good First Issues but I have a feeling I'm not experienced enough in programming to help. I still look forward to collaborating someday though!

**Comment by danielzeljko** [comment]
The official django tutorial is a great place to start learning Django. The project is open and friendly to first time devs. At times I also do pair programming with contributors. You're more than welcome to take this offer up!

> Edit: I have also noticed that when you change the site's language to Spanish, re-entering the page makes it translate back into English even though the language settings still show Spanish as the selected language. I had to click the "Go" button again for it to change into Spanish.

Hmm that's strange. If you pressed `go` after selecting a language, then the UI should stay in that language on refresh, unless your browser settings clears session data or cookies. If it's not too much trouble, can you record a video of the issue and which browser/device you are using?

#348

**Comment by kayomi-codes** [comment]
> The official django tutorial is a great place to start learning Django. The project is open and friendly to first time devs. At times I also do pair programming with contributors. You're more than welcome to take this offer up!

I have never worked with Python or any of its frameworks because I've been learning the HTML/CSS/JS trio, perhaps I'll try it soon. Thank you for suggesting it!

Regarding the UI translation bug, this is the video:

https://github.com/LangCorrect/server/assets/132253104/90f69e00-9466-42ef-9a9a-6e0682a7c973

I used an Android 12 phone to test it. My browser specifications are:
- Chrome
- Version 120.0.6099.144
